swagger: "2.0"
info:
  description: "Authors Haven - A social platform for the creative at heart."
  version: "1.0.0"
  title: "Authors Haven"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "www.kingsmen-ah-backend-staging.herokuapp.com"
basePath: "/"
tags:
- name: "user"
  description: "User operations"
  externalDocs:
    description: "Find out more about our Author's Haven"
    url: "http://kingsmen-ah-frontend-staging.herokuapp.com"
schemes:
- "https"
- "http"
paths:
  /register
  /login