swagger: "2.0"
info:
  description: "Authors Haven - A social platform for the creative at heart."
  version: "1.0.0"
  title: "Authors Haven"
  license:
    name: "MIT"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
host: "kingsmen-ah-backend-staging.herokuapp.com"
basePath: "/api"
tags:
- name: "user"
  description: "User operations"
schemes:
  - "https"
  - "http"
paths:
  /users:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Creates a new user in the application"
      operationId: "createUser"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "User created successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
  /user:
    post:
      tags:
      - "user"
      summary: "User login"
      description: "Logs user into the system"
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "query"
        description: "The email for login"
        required: true
        type: "string"
        format: "email"
        minLength: 5
        maxLength: 255
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
        format: "password"
        minLength: 5
        maxLength: 255
      responses:
        200:
          description: "login successful"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid email/password supplied"
definitions:
  User:
    type: "object"
    required:
    - username
    - email
    - password
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
        format: username
        minLength: 4
        maxLength: 100
      email:
        type: "string"
        format: "email"
        minLength: 5
        maxLength: 255
      password:
        type: "string"
        format: "password"
        minLength: 5
        maxLength: 255
      bio:
        type: "string"
      image:
        type: "string"
        format: "photourl.jpeg"
      favorites:
        type: "array"
        items:
          type: "string"
      following:
        type: "integer"
        format: "int64"
    xml:
      name: "User"
  ApiResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Author's Haven"
  url: "https://github.com/andela/kingsmen-ah-backend"
  